services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: firewall_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  excellenteam-backend:
    build: 
      context: ./backend        # path to your backend Dockerfile
      dockerfile: Dockerfile    # optional if your file is named Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.dev
    command: sh -c "npx drizzle-kit push && yarn dev"

  excellenteam-frontend:
    build: ./frontend
    ports:
      - "3001:3001"

volumes:
  pgdata:
